version: '3'

services:
  nginx:
    image: nginx
    deploy:
      replicas: 2
      placement:
        constraints: [node.role != manager]
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      SERVICE_PORTS: 80
    networks:
      - service_network
    volume: 
      - /home/user1/project_kakao/pj_toy:/usr/share/nginx/html

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - service_network
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
networks:
  service_network:
    external: true
